# Nombre del flujo de trabajo que aparecerá en la pestaña "Actions" de GitHub
name: Comprobar Actualizaciones de Datos AICLE

# --- Disparadores (Triggers) ---
# ¿Cuándo se ejecuta este robot?
on:
  # 1. Ejecución manual: permite lanzarlo con un clic desde la pestaña "Actions"
  workflow_dispatch:
  
  # 2. Ejecución programada: se ejecuta automáticamente
  schedule:
    # "cron" es un formato estándar para programar tareas.
    # Esto significa "a las 4:00 AM UTC todos los lunes".
    - cron: '0 4 * * 1'

# --- Trabajos (Jobs) ---
# Definimos las tareas que tiene que hacer el robot
jobs:
  check-and-update:
    # El robot se ejecutará en un servidor virtual con la última versión de Ubuntu
    runs-on: ubuntu-latest

    # Pasos que ejecutará en orden
    steps:
      # Paso 1: Descargar el código de tu repositorio
      - name: Descargar el código del repositorio
        uses: actions/checkout@v3

      # Paso 2: Configurar el entorno de Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Usamos una versión estable de Python

      # Paso 3: Instalar las dependencias necesarias
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # Paso 4: Ejecutar nuestro script para descargar los PDFs
      - name: Descargar los PDFs más recientes
        run: python download_pdfs.py
        
      # Paso 5: Ejecutar el script original para extraer los datos base
      - name: Extraer datos base (sin geocodificar)
        run: python extractor.py
        
      # Paso 6: Comprobar si hay cambios y hacer commit si es necesario
      - name: Hacer commit de los nuevos datos si hay cambios
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "CI: Actualización automática de datos AICLE"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
          file_pattern: 'data/centros.json source_docs/*' # Solo hace commit si estos archivos cambian
